name: goreleaser

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.16
      - name: Generate SBOM
        uses: CycloneDX/gh-gomod-generate-sbom@v1.0.0
        with:
          args: mod -licenses -type library -json -output bom.json
          version: v1
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.8.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
